### PR TITLE
deprecate react.createClass

### PR DESCRIPTION
**Pull request by cescoferraro**
solves #7

### CODE REVIEW

**Comment by cescoferraro** [comment]
now it works

**Comment by cescoferraro** [comment]
@wiredmax also added a default prop called className so we could get a way to style the inner image the holds the flag.
Maybe should update the readme as well. Just let me now what you think
I think that solves #8

**Comment by cvburgess** [comment]
@wiredmax any chance this gets merged? My team would like to upgrade to React 16 and this is causing major issues.

**Comment by wiredmax** [comment]
Merged and published on npm @cvburgess

**Comment by cvburgess** [comment]
Thank you!

**Pull request merged**
