### PR TITLE
Svg icons

### PR DESCRIPTION
**Pull request by omerl13**
Added SVG flags

### CODE REVIEW

**Comment by omerl13** [comment]
@wiredmax Can you review this PR? Using this package with SVG icons could really help me

**Comment by wiredmax** [comment]
Hi, I'm currently on vacation, I will be back this weekend and review this
PR.

**Review by wiredmax — APPROVED** [review]

**Comment by wiredmax** [comment]
It's now also published on npm @omerl13

**Comment by omerl13** [comment]
Great, thanks !

**Pull request merged**
